### ISSUE TITLE
PluginsManagerCMD refers to cmdrunner-2.3.jar

### ISSUE THREAD

**Issue by naga-awone** [Rbillon59/jmeter-k8s-base#4]
`meter@0f977cf15343:/opt/jmeter/apache-jmeter/bin$ cat PluginsManagerCMD.sh
#!/bin/sh

java -Djava.awt.headless=true $JVM_ARGS -jar $(dirname $0)/../lib/**cmdrunner-2.3.jar** --tool org.jmeterplugins.repository.PluginManagerCMD "$@"`

**Comment by naga-awone** [comment]
lib contains **cmdrunner-2.2.jar**  
https://github.com/Rbillon59/jmeter-k8s-base/blob/56e21a9b2f0dccddc480ac7efc35c8ceaa3f1b24/Dockerfile#L6

**Comment by vperaltac** [comment]
the plugin manager installation fails because of this, can we get a fix for this?

**Comment by Rbillon59** [comment]
@vperaltac @naga-awone  Please test again at let me know if your issue is gone. Thanks

**Comment by naga-awone** [comment]
@Rbillon59 , looks good
