### ISSUE TITLE
JMeter error - 5.4.1 - Unsupported class file major version 65

### ISSUE THREAD

**Issue by johanfol** [Rbillon59/jmeter-k8s-base#7]
Hi, when pulling the image rbillon59/jmeter-k8s-base:5.4.1, I'm getting the below error when running an older Jmeter test:

`2023-07-14 16:08:43,360 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[#48,10.244.5.169-Thread Group 1-4,5,RMI Runtime]
org.codehaus.groovy.GroovyBugError: BUG! exception in phase 'semantic analysis' in source unit 'Script4.groovy' Unsupported class file major version 65
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:905) ~[groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627) ~[groovy-3.0.7.jar:3.0.7]
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389) ~[groovy-3.0.7.jar:3.0.7]
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332) ~[groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163) ~[groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154) ~[groovy-3.0.7.jar:3.0.7]
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330) ~[groovy-3.0.7.jar:3.0.7]
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314) ~[groovy-3.0.7.jar:3.0.7]
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257) ~[groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:336) ~[groovy-jsr223-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:153) ~[groovy-jsr223-3.0.7.jar:3.0.7]
`

This error seems to be indicative of a version of Java > Java 8 which is the latest version supported with JMeter v5.4.1. Is it possible that the image is building with a newer version of Java, which is causing the error?

**Comment by Rbillon59** [comment]
Hello, yes I recently bumped the Java version from Java 14 to Java 21 https://github.com/Rbillon59/jmeter-k8s-base/pull/6

To address arm64 compatibility.

I will dig this issue as JMeter is only announcing a Java 8+ requirement.

Did you try with other JMeter versions by any chance ?

**Comment by johanfol** [comment]
No, but I tried on my local machine with a different Java version, and there Jmeter 5.4.1 is working. I've got Java installed:
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

I'm not sure if a different version of Jmeter will work with my jmx file. Will try and revert back.

**Comment by Rbillon59** [comment]
> No, but I tried on my local machine with a different Java version, and there Jmeter 5.4.1 is working. I've got Java installed:
> java version "1.8.0_341"
> Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
> Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)
> 
> I'm not sure if a different version of Jmeter will work with my jmx file. Will try and revert back. 

I'm not sure to understand correctly what you're trying to achieve.

Are you trying to pull this image in a Kubernetes cluster context and getting the above error when the pod is starting?

Or are you trying to use that image locally / in a docker only environment?

I will try to use Java 21 with Jmeter 5.4.1 locally and see

**Comment by johanfol** [comment]
I want to pull the image rbillon59/jmeter-k8s-base:5.4.1 into a kubernetes instance and expect the image to work. 

After getting the error, I installed pure JMeter 5.4.1 onto my local machine (not kubernetes), with the java version stated above. Then everything works. 

But the issue still persists that JMeter does not seem to work with the version of Java installed on the rbillon59/jmeter-k8s-base:5.4.1 image.

**Comment by Rbillon59** [comment]
Kubernetes version : 

```
serverVersion:
  buildDate: "2022-09-22T05:25:21Z"
  compiler: gc
  gitCommit: 5835544ca568b757a8ecae5c153f317e5736700e
  gitTreeState: clean
  gitVersion: v1.25.2
  goVersion: go1.19.1
  major: "1"
  minor: "25"
  platform: linux/amd64
```

JMeter version : `5.4.1`
![Screenshot at 11-31-55](https://github.com/Rbillon59/jmeter-k8s-base/assets/17565349/86d350b6-126e-43c1-9232-d94fd5a3a480)

Openjdk version : `21-ea`
![Screenshot at 11-29-12](https://github.com/Rbillon59/jmeter-k8s-base/assets/17565349/d96275fb-7b29-4329-8226-0d7a8be70344)


JMeter performing a test : 
![Screenshot at 11-30-00](https://github.com/Rbillon59/jmeter-k8s-base/assets/17565349/a673a2b5-015c-43ba-8b88-22ff8faeee52)


I'm not seeing the error. Could you describe a bit more your env etc .. ?

Thanks

**Comment by johanfol** [comment]
From reading the error, I believe it's something to do with Groovy scripts specifically, when running the jmx test. 

If I run the same jmx on my machine, it works, when passing it to the kubes instance to run, I get the error:
![image](https://github.com/Rbillon59/jmeter-k8s-base/assets/36838637/2fb0317f-6783-4db3-8ce4-b394e2e9bab8)

**Comment by johanfol** [comment]
I've tested this test file works with Jmeter 5.4.3 with latest version of Java on my machine, so will do a run from Kubernetes now and post outcome.

**Comment by johanfol** [comment]
The 5.4.1 image is causing this error on Slave startup, specifically the "telegraf" container:
![image](https://github.com/Rbillon59/jmeter-k8s-base/assets/36838637/035ecebc-d859-4379-9128-57ed702ca206)

Causing this in master:

![image](https://github.com/Rbillon59/jmeter-k8s-base/assets/36838637/4ca6e237-2737-451a-869d-c83ab189fb55)

**Comment by Rbillon59** [comment]
The Telegraf container is querying the jmeter-slave Jolokia agent, so if the JMeter process crash, the Jolokia agent is not able to start properly and so the telegraf side-car cannot query it, so the error.

I've red [here](https://github.com/grails/grails-core/issues/12152) that 

```
JDK 17 requires [asm 9.1](https://asm.ow2.io/versions.html#9.1) and [Groovy 3.0.8](https://github.com/apache/groovy/commit/d27994ea1f516894423980c958b65c8c02fb9395) is the first version to support it.
```

I just manually pushed an image based on openJDK 16. Could you try using this image : `rbillon59/jmeter-k8s-base:5.4.1-jdk-16` ?

Thanks

**Comment by Rbillon59** [comment]
Any news @johanfol ?

**Comment by johanfol** [comment]
Hi Romain, we upgraded to latest version and did fixes that was required, we also re-wrote the groovy scripts (which seemed like the issue), and now everything is okay. We did not end up testing the image you suggested. 

We can close the issue from our side - the fix for us was to upgrade to latest version.

**Comment by Rbillon59** [comment]
All right, Glad you end up with a working state !
